baseURL = 'https://lwbuchanan.github.io/'
languageCode = 'en-us'
title = 'Luke Buchanan'
theme = 'archie_custom'
copyright = "Â© Luke Buchanan"

[caches]
    [caches.images]
        dir = ":cacheDir/images"

[params]
    mode="toggle"
	useCDN=false
	subtitle = "subtitle"

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/lwbuchanan"

[[params.social]]
name = "LinkedIn"
icon = "linkedin"
url = "https://www.linkedin.com/in/luke-buchanan-6145b81b3/"


[[menu.main]]
name = "Resume"
url = "/resume"
weight = 1

[[menu.main]]
name = "Projects"
url = "/projects"
weight = 2

[[menu.main]]
name = "Posts"
url = "/posts"
weight = 3
