baseURL = 'https://lwbuchanan.github.io/'
languageCode = 'en-us'
title = 'Luke Buchanan'
theme = 'archie'
copyright = "Â© Luke Buchanan"

[caches]
    [caches.images]
        dir = ":cacheDir/images"

[params]
    mode="auto"
	useCDN=false
	subtitle = "subtitle"

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/lwbuchanan"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Projects"
url = "/projects"
weight = 2
